### ISSUE TITLE
[Inference] AssertionError: Non-existent key: --output

### ISSUE THREAD

**Issue by BupyeongHealer** [facebookresearch/Mask2Former#11]
Hello! Thank you for sharing.
I found some error in inference code (demo.py).
There is non-existent key, --output.

I modified the code for saving, you need to modify the code for saving.

```console
(detectron) hello96min@rvi-node001:~/minseok/Mask2Former/demo$ python3 demo.py --config-file /home/hello96min/minseok/Mask2Former/configs/coco/panoptic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_100ep.yaml --input ~/minseok/image-inpainting/datasets_dgm/sample_data/images/images_0.png --opts MODEL.WEIGHTS /home/hello96min/minseok/Mask2Former/configs/coco/panoptic-segmentation/model_final_f07440.pkl --output ./1.png
[12/14 22:37:14 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/home/hello96min/minseok/Mask2Former/configs/coco/panoptic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_100ep.yaml', input=['/home/hello96min/minseok/image-inpainting/datasets_dgm/sample_data/images/images_0.png'], opts=['MODEL.WEIGHTS', '/home/hello96min/minseok/Mask2Former/configs/coco/panoptic-segmentation/model_final_f07440.pkl', '--output', './1.png'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    cfg = setup_cfg(args)
  File "demo.py", line 40, in setup_cfg
    cfg.merge_from_list(args.opts)
  File "/home/hello96min/yes/envs/detectron/lib/python3.8/site-packages/fvcore/common/config.py", line 143, in merge_from_list
    return super().merge_from_list(cfg_list)
  File "/home/hello96min/yes/envs/detectron/lib/python3.8/site-packages/yacs/config.py", line 243, in merge_from_list
    _assert_with_logging(subkey in d, "Non-existent key: {}".format(full_key))
  File "/home/hello96min/yes/envs/detectron/lib/python3.8/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Non-existent key: --output
```

**Comment by bowenc0221** [comment]
All flags (e.g., `--output`) should be in front of `--opts`.

**Comment by BupyeongHealer** [comment]
It works! I appreciate it.
