### ISSUE TITLE
    raise ValueError("matrix contains invalid numeric entries")

### ISSUE THREAD

**Issue by AhmadZobairSurosh** [facebookresearch/Mask2Former#127]
Hi. Thanks for your great project.

I have been trying to train Mask2Former on my own dataset but after 11859 iters, i get the following error.
Could it be because of my lr? 

Any help is appreciated!

Cheers

```

[07/30 00:17:57] d2.utils.events INFO:  eta: 5:48:54  iter: 11859  total_loss: 45.91  loss_ce: 1.061  loss_mask: 0.1516  loss_dice: 3.623  loss_ce_0: 0.4758  loss_mask_0: 0.1392  loss_dice_0: 3.208  loss_ce_1: 0.6885  loss_mask_1: 0.186  loss_dice_1: 3.529  loss_ce_2: 0.7608  loss_mask_2: 0.1806  loss_dice_2: 3.595  loss_ce_3: 0.8406  loss_mask_3: 0.137  loss_dice_3: 3.551  loss_ce_4: 1.091  loss_mask_4: 0.1918  loss_dice_4: 3.637  loss_ce_5: 1.09  loss_mask_5: 0.2125  loss_dice_5: 3.718  loss_ce_6: 0.7337  loss_mask_6: 0.1847  loss_dice_6: 3.558  loss_ce_7: 0.9319  loss_mask_7: 0.1548  loss_dice_7: 3.535  loss_ce_8: 0.8802  loss_mask_8: 0.1762  loss_dice_8: 3.604  time: 1.1627  data_time: 0.0892  lr: 0.001  max_mem: 8978M
[07/30 00:18:11] d2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/floorplans/Mask2Former/mask2former/maskformer_model.py", line 209, in forward
    losses = self.criterion(outputs, targets)
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/floorplans/Mask2Former/mask2former/modeling/criterion.py", line 222, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/floorplans/Mask2Former/mask2former/modeling/matcher.py", line 179, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/floorplans/Mask2Former/mask2former/modeling/matcher.py", line 151, in memory_efficient_forward
    indices.append(linear_sum_assignment(C))
  File "/home/vvz/anaconda3/envs/mask2former/lib/python3.6/site-packages/scipy/optimize/_lsap.py", line 93, in linear_sum_assignment
    raise ValueError("matrix contains invalid numeric entries")
ValueError: matrix contains invalid numeric entries
[07/30 00:18:11] d2.engine.hooks INFO: Overall training speed: 11869 iterations in 3:50:01 (1.1628 s / it)
[07/30 00:18:11] d2.engine.hooks INFO: Total training time: 3:50:17 (0:00:16 on hooks)
[07/30 00:18:11] d2.utils.events INFO:  eta: 5:48:40  iter: 11871  total_loss: 47.28  loss_ce: 1.052  loss_mask: 0.1669  loss_dice: 3.675  loss_ce_0: 0.5069  loss_mask_0: 0.1637  loss_dice_0: 3.306  loss_ce_1: 0.6921  loss_mask_1: 0.1929  loss_dice_1: 3.571  loss_ce_2: 0.8097  loss_mask_2: 0.1854  loss_dice_2: 3.697  loss_ce_3: 0.8414  loss_mask_3: 0.1516  loss_dice_3: 3.655  loss_ce_4: 1.114  loss_mask_4: 0.2051  loss_dice_4: 3.781  loss_ce_5: 1.079  loss_mask_5: 0.2326  loss_dice_5: 3.772  loss_ce_6: 0.7579  loss_mask_6: 0.189  loss_dice_6: 3.71  loss_ce_7: 0.9967  loss_mask_7: 0.1659  loss_dice_7: 3.699  loss_ce_8: 0.8863  loss_mask_8: 0.1786  loss_dice_8: 3.685  time: 1.1628  data_time: 0.0814  lr: 0.001  max_mem: 8978M
```

**Comment by AhmadZobairSurosh** [comment]
Solved in #58 .

Cheers
