### ISSUE TITLE
TypeError: 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by 1poorman** [facebookresearch/Mask2Former#140]
When I use mask2former for instance_segmentation to train my coco-style  dataset, I meet a problem that I can 't solve by myself.

`Traceback (most recent call last):
  File "train_net1.py", line 414, in <module>
    args=(args,),
  File "/media/btbu/gt/HCH/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net1.py", line 402, in main
    return trainer.train()
  File "/media/btbu/gt/HCH/detectron2/detectron2/engine/defaults.py", line 489, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/btbu/gt/HCH/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/media/btbu/gt/HCH/detectron2/detectron2/engine/defaults.py", line 499, in run_step
    self._trainer.run_step()
  File "/media/btbu/gt/HCH/detectron2/detectron2/engine/train_loop.py", line 391, in run_step
    data = next(self._data_loader_iter)
  File "/media/btbu/gt/HCH/detectron2/detectron2/data/common.py", line 179, in __iter__
    for d in self.dataset:
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/btbu/gt/HCH/detectron2/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/media/btbu/gt/HCH/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/media/btbu/gt/HCH/Mask2Former-main/mask2former/data/dataset_mappers/coco_instance_new_baseline_dataset_mapper.py", line 166, in __call__
    for obj in dataset_dict.pop("annotations")
  File "/media/btbu/gt/HCH/Mask2Former-main/mask2former/data/dataset_mappers/coco_instance_new_baseline_dataset_mapper.py", line 167, in <listcomp>
    if obj.get("iscrowd", 0) == 0
  File "/media/btbu/gt/HCH/detectron2/detectron2/data/detection_utils.py", line 297, in transform_instance_annotations
    p.reshape(-1) for p in transforms.apply_polygons(polygons)
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 297, in <lambda>
    return lambda x: self._apply(x, name)
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 291, in _apply
    x = getattr(t, meth)(x)
  File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 724, in apply_polygons
    for poly in cropped:
TypeError: 'MultiPolygon' object is not iterable
`
what should I do?

**Comment by bowenc0221** [comment]
Maybe try the https://github.com/facebookresearch/Mask2Former/blob/main/mask2former/data/dataset_mappers/mask_former_instance_dataset_mapper.py?

**Comment by 1poorman** [comment]
i have solved, torch is to low. just follow the readme is ok. 

> When I use mask2former for instance_segmentation to train my coco-style dataset, I meet a problem that I can 't solve by myself.
> 
> `Traceback (most recent call last): File "train_net1.py", line 414, in <module> args=(args,), File "/media/btbu/gt/HCH/detectron2/detectron2/engine/launch.py", line 82, in launch main_func(*args) File "train_net1.py", line 402, in main return trainer.train() File "/media/btbu/gt/HCH/detectron2/detectron2/engine/defaults.py", line 489, in train super().train(self.start_iter, self.max_iter) File "/media/btbu/gt/HCH/detectron2/detectron2/engine/train_loop.py", line 149, in train self.run_step() File "/media/btbu/gt/HCH/detectron2/detectron2/engine/defaults.py", line 499, in run_step self._trainer.run_step() File "/media/btbu/gt/HCH/detectron2/detectron2/engine/train_loop.py", line 391, in run_step data = next(self._data_loader_iter) File "/media/btbu/gt/HCH/detectron2/detectron2/data/common.py", line 179, in __iter__ for d in self.dataset: File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__ data = self._next_data() File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) TypeError: Caught TypeError in DataLoader worker process 3. Original Traceback (most recent call last): File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/btbu/gt/HCH/detectron2/detectron2/data/common.py", line 43, in __getitem__ data = self._map_func(self._dataset[cur_idx]) File "/media/btbu/gt/HCH/detectron2/detectron2/utils/serialize.py", line 23, in __call__ return self._obj(*args, **kwargs) File "/media/btbu/gt/HCH/Mask2Former-main/mask2former/data/dataset_mappers/coco_instance_new_baseline_dataset_mapper.py", line 166, in __call__ for obj in dataset_dict.pop("annotations") File "/media/btbu/gt/HCH/Mask2Former-main/mask2former/data/dataset_mappers/coco_instance_new_baseline_dataset_mapper.py", line 167, in <listcomp> if obj.get("iscrowd", 0) == 0 File "/media/btbu/gt/HCH/detectron2/detectron2/data/detection_utils.py", line 297, in transform_instance_annotations p.reshape(-1) for p in transforms.apply_polygons(polygons) File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 297, in <lambda> return lambda x: self._apply(x, name) File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 291, in _apply x = getattr(t, meth)(x) File "/home/btbu/Anaconda/enter/envs/detectron2/lib/python3.7/site-packages/fvcore/transforms/transform.py", line 724, in apply_polygons for poly in cropped: TypeError: 'MultiPolygon' object is not iterable ` what should I do?

i have solved, torch is to low. just follow the readme is ok.

**Comment by nannigath** [comment]
@1poorman how did you solve it?

**Comment by 1poorman** [comment]
the torch's version that i installed is incommensurate,so i change it .




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月14日(星期三) 下午5:06
收件人: ***@***.***&gt;; 
抄送: "Лас - ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [facebookresearch/Mask2Former] TypeError: &#39;MultiPolygon&#39; object is not iterable (Issue #140)





 
@1poorman how did you solve it?
