### ISSUE TITLE
RuntimeError: expand(CUDABoolType) in train mapillary semantic segmentation

### ISSUE THREAD

**Issue by yufeng89** [facebookresearch/Mask2Former#165]
when  I train mapillary semantic segmentation,error occur below:

Traceback (most recent call last):
File "/workspace/Mask2Former/train_net.py", line 322, in
launch(
File "/workspace/detectron2/detectron2/engine/launch.py", line 82, in launch
main_func(*args)
File "/workspace/Mask2Former/train_net.py", line 316, in main
return trainer.train()
File "/workspace/detectron2/detectron2/engine/defaults.py", line 484, in train
super().train(self.start_iter, self.max_iter)
File "/workspace/detectron2/detectron2/engine/train_loop.py", line 149, in train
self.run_step()
File "/workspace/detectron2/detectron2/engine/defaults.py", line 494, in run_step
self._trainer.run_step()
File "/workspace/detectron2/detectron2/engine/train_loop.py", line 413, in run_step
loss_dict = self.model(data)
File "/root/anaconda3/envs/segment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/workspace/Mask2Former/mask2former/maskformer_model.py", line 204, in forward
targets = self.prepare_targets(gt_instances, images)
File "/workspace/Mask2Former/mask2former/maskformer_model.py", line 271, in prepare_targets
padded_masks[:, : gt_masks.shape[1], : gt_masks.shape[2]] = gt_masks
RuntimeError: expand(CUDABoolType{[21, 1024, 1024, 3]}, size=[21, 1024, 1024]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)

**Comment by yufeng89** [comment]
Traceback (most recent call last):
File "/workspace/Mask2Former/train_net.py", line 322, in <module>
launch(
File "/workspace/detectron2/detectron2/engine/launch.py", line 82, in launch
main_func(*args)
File "/workspace/Mask2Former/train_net.py", line 316, in main
return trainer.train()
File "/workspace/detectron2/detectron2/engine/defaults.py", line 484, in train
super().train(self.start_iter, self.max_iter)
File "/workspace/detectron2/detectron2/engine/train_loop.py", line 149, in train
self.run_step()
File "/workspace/detectron2/detectron2/engine/defaults.py", line 494, in run_step
self._trainer.run_step()
File "/workspace/detectron2/detectron2/engine/train_loop.py", line 413, in run_step
loss_dict = self.model(data)
File "/root/anaconda3/envs/segment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/workspace/Mask2Former/mask2former/maskformer_model.py", line 204, in forward
targets = self.prepare_targets(gt_instances, images)
File "/workspace/Mask2Former/mask2former/maskformer_model.py", line 271, in prepare_targets
padded_masks[:, : gt_masks.shape[1], : gt_masks.shape[2]] = gt_masks
RuntimeError: expand(CUDABoolType{[21, 1024, 1024, 3]}, size=[21, 1024, 1024]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)
