### ISSUE TITLE
KeyError: "No object named 'MaskFormerHead' found in 'SEM_SEG_HEADS' registry!"

### ISSUE THREAD

**Issue by josyulakrishna** [facebookresearch/Mask2Former#199]
Hi I have followed all the instruction and installed detectron2 and mask2former, however I when I run the basic "demo.py" file I get the following error 

```
KeyError: "No object named 'MaskFormerHead' found in 'SEM_SEG_HEADS' registry!"
```

The complete error log is shown below: 

```
python demo.py --config-file=/home/josyula/Programs/branchingpointdetection/detectron2/Mask2Former/configs/youtubevis_2019/video_maskformer2_R50_bs16_8ep.yaml
[05/23 13:12:24 detectron2]: Arguments: Namespace(config_file='/home/josyula/Programs/branchingpointdetection/detectron2/Mask2Former/configs/youtubevis_2019/video_maskformer2_R50_bs16_8ep.yaml', video_input=None, input=None, output=None, save_frames=False, confidence_threshold=0.5, opts=[])
Traceback (most recent call last):
  File "/home/josyula/Programs/branchingpointdetection/detectron2/Mask2Former/demo_video/demo.py", line 118, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/Mask2Former/demo_video/predictor.py", line 39, in __init__
    self.predictor = VideoPredictor(cfg)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/detectron2/engine/defaults.py", line 282, in __init__
    self.model = build_model(self.cfg)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/josyula/Programs/branchingpointdetection/detectron2/Mask2Former/demo_video/../mask2former_video/video_maskformer_model.py", line 93, in from_config
    sem_seg_head = build_sem_seg_head(cfg, backbone.output_shape())
  File "/home/josyula/Programs/branchingpointdetection/detectron2/detectron2/modeling/meta_arch/semantic_seg.py", line 142, in build_sem_seg_head
    return SEM_SEG_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/home/josyula/miniconda3/lib/python3.9/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'MaskFormerHead' found in 'SEM_SEG_HEADS' registry!"

```

**Comment by haixiongli** [comment]
did you solve this problem? I met the same problem, thanks.

**Comment by josyulakrishna** [comment]
> did you solve this problem? I met the same problem, thanks.

 It’s been quite a while I don’t know what change I have made but the complete working code is here 

https://github.com/josyulakrishna/detectron2_pruning 

Good luck
