### ISSUE TITLE
Train coco dataset error

### ISSUE THREAD

**Issue by Kenneth-X** [facebookresearch/Mask2Former#41]
i followed the instruction:  
[https://github.com/facebookresearch/Mask2Former/blob/main/datasets/README.md](url) and perpare the coco datasets.

I have already run demo successfully but the error occur when i running train scrip：
`python train_net.py --num-gpus 8   --config-file configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml`

which is followed:
`
[02/01 14:43:34 mask2former.data.dataset_mappers.coco_panoptic_new_baseline_dataset_mapper]: [COCOPanopticNewBaselineDatasetMapper] Full TransformGens used in training: [RandomFlip(), ResizeScale(min_scale=0.1, max_scale=2.0, target_height=1024, target_width=1024), FixedSizeCrop(crop_size=(1024, 1024))]
[02/01 14:43:41 d2.data.build]: Using training sampler TrainingSampler
[02/01 14:43:41 d2.data.common]: Serializing 118287 elements to byte tensors and concatenating them all ...
[02/01 14:43:42 d2.data.common]: Serialized dataset takes 78.29 MiB
[02/01 14:43:51 fvcore.common.checkpoint]: [Checkpointer] Loading from model_final_94dc52.pkl ...
[02/01 14:43:51 fvcore.common.checkpoint]: Reading a file from 'MaskFormer Model Zoo'
WARNING [02/01 14:43:51 mask2former.modeling.transformer_decoder.mask2former_transformer_decoder]: Weight format of MultiScaleMaskedTransformerDecoder have changed! Please upgrade your models. Applying automatic conversion now ...
[02/01 14:43:51 d2.engine.train_loop]: Starting training from iteration 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/home/xt.xie/workspace/code/Mask2Former-main/train_net.py", line 321, in <module>
    launch(
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/xt.xie/workspace/code/Mask2Former-main/train_net.py", line 315, in main
    return trainer.train()
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xt.xie/workspace/code/Mask2Former-main/mask2former/maskformer_model.py", line 209, in forward
    losses = self.criterion(outputs, targets)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xt.xie/workspace/code/Mask2Former-main/mask2former/modeling/criterion.py", line 222, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xt.xie/workspace/code/Mask2Former-main/mask2former/modeling/matcher.py", line 179, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xt.xie/workspace/code/Mask2Former-main/mask2former/modeling/matcher.py", line 122, in memory_efficient_forward
    tgt_mask = point_sample(
  File "/home/xt.xie/.local/lib/python3.9/site-packages/detectron2/projects/point_rend/point_features.py", line 39, in point_sample
    output = F.grid_sample(input, 2.0 * point_coords - 1.0, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py", line 3836, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has c10::Half and grid has float
`

**Comment by bowenc0221** [comment]
Please use PyTorch >= 1.9

**Comment by Kenneth-X** [comment]
thanks, it helps me a lot
