### ISSUE TITLE
ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by haochenheheda** [facebookresearch/Mask2Former#59]
```
Traceback (most recent call last):
  File "train_net.py", line 327, in <module>
    args=(args,),
  File "/home/haochen/workspace/project/VIS/Mask2Former/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 315, in main
    return trainer.train()
  File "/home/haochen/workspace/project/VIS/Mask2Former/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/haochen/workspace/project/VIS/Mask2Former/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/haochen/workspace/project/VIS/Mask2Former/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/haochen/workspace/project/VIS/Mask2Former/detectron2/detectron2/engine/train_loop.py", line 396, in run_step
    loss_dict = self.model(data)
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haochen/workspace/project/VIS/Mask2Former/mask2former/maskformer_model.py", line 209, in forward
    losses = self.criterion(outputs, targets)
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haochen/workspace/project/VIS/Mask2Former/mask2former/modeling/criterion.py", line 222, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/haochen/workspace/project/VIS/Mask2Former/mask2former/modeling/matcher.py", line 179, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/haochen/workspace/project/VIS/Mask2Former/mask2former/modeling/matcher.py", line 151, in memory_efficient_forward
    indices.append(linear_sum_assignment(C))
  File "/home/haochen/anaconda3/envs/mask2former/lib/python3.7/site-packages/scipy/optimize/_lsap.py", line 100, in linear_sum_assignment
    return _lsap_module.calculate_assignment(cost_matrix)
ValueError: matrix contains invalid numeric entries
```

Still happen when I changed base_lr to 0.00001

**Comment by haochenheheda** [comment]
I changed the eps in ADAMW form 1e-8 to 1e-3, and it's solved. 
I think it's because the 1e-8 will be 0 in float16

**Comment by saidineshpola** [comment]
@haochenheheda can you please mention where to change the eps in ADAMW. I am getting very high loss even after training normal epochs. I am using single GPU for training the custom dataset.

**Comment by sushilkhadkaanon** [comment]
@saidineshpola @haochenheheda from where to change eps in ADAMW?

**Comment by SergiyShebotnov** [comment]
> I changed the eps in ADAMW form 1e-8 to 1e-3, and it's solved. I think it's because the 1e-8 will be 0 in float16

Where would one change it in Detectron2?
