### ISSUE TITLE
Question about Resource temporarily unavailable

### ISSUE THREAD

**Issue by kunjing96** [facebookresearch/Mask2Former#88]
[04/23 20:31:50] d2.utils.events INFO:  eta: 1 day, 5:05:25  iter: 169979  total_loss: 44.71  loss_ce: 2.769  loss_mask: 0.5348  loss_dice: 1.691  loss_ce_0: 4.793  loss_mask_0: 0.6999  loss_dice_0: 2.144  loss_ce_1: 3.016  loss_mask_1: 0.6082  loss_dice_1: 1.871  loss_ce_2: 2.928  loss_mask_2: 0.542  loss_dice_2: 1.83  loss_ce_3: 2.787  loss_mask_3: 0.5507  loss_dice_3: 1.773  loss_ce_4: 2.771  loss_mask_4: 0.5256  loss_dice_4: 1.78  loss_ce_5: 2.306  loss_mask_5: 0.3708  loss_dice_5: 1.272  loss_ce_6: 2.251  loss_mask_6: 0.3651  loss_dice_6: 1.338  loss_ce_7: 0  loss_mask_7: 0  loss_dice_7: 0  loss_ce_8: 0  loss_mask_8: 0  loss_dice_8: 0  time: 0.5295  data_time: 0.0077  lr: 0.0001  max_mem: 16778M
[04/23 20:32:00] fvcore.common.checkpoint INFO: Saving checkpoint to ./output/model_0169999.pth
[04/23 20:32:02] d2.data.dataset_mapper INFO: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[04/23 20:32:02] d2.data.common INFO: Serializing 5000 elements to byte tensors and concatenating them all ...
[04/23 20:32:02] d2.data.common INFO: Serialized dataset takes 3.68 MiB
[04/23 20:45:57] d2.evaluation.panoptic_evaluation INFO: Writing all panoptic predictions to /tmp/panoptic_evalyy05c1js ...
[04/23 20:46:04] d2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/jingkun/detectron2/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/home/jingkun/detectron2/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/jingkun/detectron2/detectron2/engine/hooks.py", line 555, in after_step
    self._do_eval()
  File "/home/jingkun/detectron2/detectron2/engine/hooks.py", line 528, in _do_eval
    results = self._func()
  File "/home/jingkun/detectron2/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/jingkun/AutoUniSegFormer/AutoUniSegFormer/train_net.py", line 549, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, cfg.MODE, cfg.SUBNET, cfg.SEARCH_SPACE)
  File "/home/jingkun/AutoUniSegFormer/AutoUniSegFormer/train_net.py", line 251, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/jingkun/detectron2/detectron2/evaluation/evaluator.py", line 93, in evaluate
    result = evaluator.evaluate()
  File "/home/jingkun/detectron2/detectron2/evaluation/panoptic_evaluation.py", line 144, in evaluate
    pq_res = pq_compute(
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/site-packages/panopticapi/evaluation.py", line 219, in pq_compute
    pq_stat = pq_compute_multi_core(matched_annotations_list, gt_folder, pred_folder, categories)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/site-packages/panopticapi/evaluation.py", line 172, in pq_compute_multi_core
    workers = multiprocessing.Pool(processes=cpu_num)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/home/jingkun/anaconda3/envs/ViT/lib/python3.8/multiprocessing/util.py", line 429, in spawnv_passfds
    return _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable

I was able to successfully achieve the results reported in the paper for the first time, but when I tried to use smaller batch size to reproduce it on two GPUs, I often get an error in an uncertain evaluation. See above for details.

I use "python train_net.py  --num-gpus 2 --config-file configs/coco/panoptic-segmentation/swin/maskformer2_swin_tiny_bs16_50ep.yaml" to reproduce it.

**Comment by bowenc0221** [comment]
This seems to be an issue related to the panoptic api. One solution is to not do any evaluation during training.
